<%
REM =========================================================================
REM  /Constants.inc
REM -------------------------------------------------------------------------
REM Nome     : Constates do modelo SEDF
REM Descricao: Menu para o modelo SEDF
REM Home     : http://www.acheiescola.com.br/
REM Criacao  : 22/03/2000 14:05
REM Autor    : Alexandre Vinhadelli Papadópolis
REM Versao   : 1.0.0.0
REM Local    : Brasília - DF
REM Companhia: 2000 by SBPI Sociedade Brasileira para a Pesquisa em Informática
REM -------------------------------------------------------------------------
  
  Const conSMTPServer = "smtp.cabonet.com.br"
  Const conHead	      = "SIGE Web"

  Const conScriptTimeout    = 60
  Const conSessionTimeout   = 300
  Const conConnectionString ="Provider=sqloledb.1;Data Source=jupiter;UID=intweb;PWD=xyz345aix;Initial Catalog=SIGE"
  Const conVirtualPath      = "/sige/"
  Const conSite	            = "http://netuno:8080"

  Const conWhatPrincipal  = "110"
  Const conWhatCabecalho  = "111"
  Const conWhatRodape     = "112"
  Const conWhatQuem       = "113"
  Const conWhatExNoticia  = "114"
  Const conWhatExCalend   = "115"
  Const conWhatValida     = "116"
  Const conWhatExFale     = "117"
  Const conWhatMenu       = "118"
  Const conWhatSenha      = "119"
  Const conWhatExBoletim  = "120"
  Const conWhatExGrade    = "121"
  Const conWhatExMens     = "122"
  Const conWhatGravaMens  = "123"
  Const conWhatManut      = "108"
  Const conWhatEsquerda   = "124"
  Const conWhatFinanceira = "126"
  Const conWhatBoleto     = "127"
  Const conWhatGabarito   = "128"
  Const conWhatTopo       = "129"
  Const conWhatProfessor  = "140"
  Const conWhatArquivo	  = "143"
  Const conWhatSite       = "144"
  

  Const conListEmpresaUF = "101"

  Const conListCampoTipo          = "141"
  Const conListCampoDelimitador   = "142"

  ' Constantes do sistema
  Const conAspas             = """"
  Const conConnectionTimeout = 300
  Const conCommandTimeout    = 300
  Const conSelectAll         = "SELECT * FROM "
  Const conTotalBlocks       = "/8 - "
  Const conBackTo            = "<BR>Voltar para o cadastro "
  Const conToMakeSystem      = "MS"
  Const conOptions           = "O"



REM -------------------------------------------------------------------------
REM Fim do Constants.inc
REM =========================================================================
%>